### ISSUE TITLE
Error attemtping to send syslogmessage

### ISSUE THREAD

**Issue by athelu** [poshsecurity/Posh-SYSLOG#15]
attempting to send a syslog message to a target system and receiving the following error:

> Multiple ambiguous overloads found for ".ctor" and the argument count: "1".
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\posh-syslog\functions\Disconnect-UDPClient.ps1:21 char:5
+     [OutputType($null)]
+     ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

Multiple ambiguous overloads found for ".ctor" and the argument count: "1".
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\posh-syslog\functions\Disconnect-UDPClient.ps1:21 char:5
+     [OutputType($null)]
+     ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

With the code samples from the original author site i was able to send Syslog messages between these two systems.

**Comment by kjacobsen** [comment]
Hi,

What version of the module and what version of PowerShyell are you using?

**Comment by kjacobsen** [comment]
Hi,

This issue will be addressed as part of the version 5 release in the next few days.

**Comment by kjacobsen** [comment]
Hi,

This issue should now be resolved.
